FROM nginx

MAINTAINER Johannes Unterstein <junterstein@mesosphere.io>

COPY nginx-neo4j.crt /etc/nginx/ssl/nginx-neo4j.crt
COPY nginx-neo4j.key /etc/nginx/ssl/nginx-neo4j.key
COPY nginx.conf /etc/nginx/conf.d/default.conf 
